@startuml
start

:Игрок начинает свой  ход;

while (Есть карты для розыгрыша?)
    :Сыграть карту;

    if (Тип карты атака?) then (Да)
    :Выбрать цель;
    :Нанести урон, 
    если цель не
    защищается;

    else ()
    if (Тип карты хилл?) then (Да)
    :Восстановить здоровье;

    elseif (Влияет на руку?) then (Добор карт)
    :Взять карты;

    else(Расширение руки)
    :Увеличить 
    лимит руки;

    endif
    endif

endwhile

:Купить карту из банка, если есть возможность;

:Сбросить руку;

:Набрать новую руку;

:Завершить ход;

stop
@enduml