@startuml use-case

left to right direction

actor Пользователь
actor Игрок
actor Модератор

rectangle "Игровая система" {

    Пользователь -- (Регистрация)
    Пользователь -- (Авторизация)

    Пользователь -- (Создать игру)
    Пользователь -- (Присоединиться к игре)

    Пользователь -- (Просмотр правил игры)
    Пользователь -- (Просмотр каталога карт)

    Игрок -- (Начать ход)
    Игрок -- (Сыграть карту)
    Игрок -- (Купить карту)
    Игрок -- (Сбросить карту)
    Игрок -- (Завершить ход)

    Модератор -- (Добавить карту)
    Модератор -- (Редактировать карту)
    Модератор -- (Удалить карту)
    Модератор -- (Бан игроков)
    Модератор -- (Завершение текущих игр)
}

@enduml